services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  ingestion-service:
    build:
      context: ../../
      dockerfile: services/ingestion-service/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  analytics-service:
    build:
      context: ../../
      dockerfile: services/analytics-service/Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  intelligence-service:
    build:
      context: ../../
      dockerfile: services/intelligence-service/Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      - redis
    env_file:
      - ../../.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  redis_data: